version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqtt-publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    environment:
      - BROKER_IP=mqtt-broker
      - TOPIC=sensors/data
    depends_on:
      - mqtt-broker
    deploy:
      replicas: 3

  mqtt-subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    environment:
      - BROKER_IP=mqtt-broker
      - TOPIC=sensors/data
    depends_on:
      - mqtt-broker
    volumes:
      - ./data:/data

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=sensordata
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - influxdb-data:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
  grafana-data:
