FROM ubuntu:focal

RUN apt-get update && apt-get install -y mosquitto-clients

COPY subscriber.sh /usr/local/bin/subscriber.sh
RUN chmod +x /usr/local/bin/subscriber.sh

CMD ["sh", "/usr/local/bin/subscriber.sh"]
