---

services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "health/check", "-m", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mqtt-publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    environment:
      - BROKER_IP=${BROKER_IP}
      - TOPIC=${TOPIC}
    depends_on:
      - mqtt-broker
    deploy:
      replicas: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mqtt-subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    environment:
      - BROKER_IP=${BROKER_IP}
      - TOPIC=${TOPIC}
    depends_on:
      - mqtt-broker
    volumes:
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
